### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by cs801458j** [MaengMaeng/my-buddy-introduce#2]
문제 현상: merge 이후 npm start 이슈
![image](https://user-images.githubusercontent.com/19684904/103252156-e9cbe600-49be-11eb-94bf-a9895ac6e77e.png)

### 로그파일 내용
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle my-buddy-introduce@0.1.0~prestart: my-buddy-introduce@0.1.0
6 info lifecycle my-buddy-introduce@0.1.0~start: my-buddy-introduce@0.1.0
7 verbose lifecycle my-buddy-introduce@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle my-buddy-introduce@0.1.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\LDCC\Desktop\workspace\my-buddy-introduce\node_modules\.bin;C:\Users\LDCC\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\LDCC\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio;C:\Program Files\TortoiseSVN\bin;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\nodejs;C:\Program Files (x86)\ePapyrus\PapyrusNtas;C:\Program Files (x86)\ePapyrus\PapyrusNtas\Addins;C:\Users\LDCC\AppData\Local\Programs\Python\Python36\Scripts;C:\Users\LDCC\AppData\Local\Programs\Python\Python36;C:\Users\LDCC\AppData\Local\Programs\Python\Python38\Scripts;C:\Users\LDCC\AppData\Local\Programs\Python\Python38;C:\Users\LDCC\AppData\Local\Programs\Python\Python37\Scripts;C:\Users\LDCC\AppData\Local\Programs\Python\Python37;C:\Users\LDCC\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Java\jdk1.8.0_201\bin;C:\Users\LDCC\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Bandizip;C:\apache-maven-3.6.0\bin;C:\Users\LDCC\Downloads\spring-1.1.4.RELEASE\bin;C:\Users\LDCC\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\PyCharm Community Edition 2019.3\bin;C:\Users\LDCC\AppData\Roaming\npm;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1\bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle my-buddy-introduce@0.1.0~start: CWD: C:\Users\LDCC\Desktop\workspace\my-buddy-introduce
10 silly lifecycle my-buddy-introduce@0.1.0~start: Args: [ '/d /s /c', 'npm-run-all --parallel start:**' ]
11 silly lifecycle my-buddy-introduce@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle my-buddy-introduce@0.1.0~start: Failed to exec start script
13 verbose stack Error: my-buddy-introduce@0.1.0 start: `npm-run-all --parallel start:**`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid my-buddy-introduce@0.1.0
15 verbose cwd C:\Users\LDCC\Desktop\workspace\my-buddy-introduce
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error my-buddy-introduce@0.1.0 start: `npm-run-all --parallel start:**`
22 error Exit status 1
23 error Failed at the my-buddy-introduce@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

현재 해결하려고 시도중
- https://stackoverflow.com/questions/42308879/how-to-solve-npm-error-npm-err-code-elifecycle

혹시 전에 비슷한 현상 겪었다면 해결 방법 공유부탁드립니다^.^

**Comment by cs801458j** [comment]
https://stackoverflow.com/questions/42308879/how-to-solve-npm-error-npm-err-code-elifecycle
- 이 방법으로 해결 완료... 캐시 문제인가?

**Comment by MaengMaeng** [comment]
아마 pull 받은 후에 npm 모듈을 설치를 안하고 바로 실행해서 그런 것 같습니다!

실행하기 전에 `npm install` 하고 난 후에 `npm start` 하시면 실행 될 것 같습니다~
