### ISSUE TITLE
Passport 세션 문제

### ISSUE THREAD

**Issue by MaengMaeng** [MaengMaeng/my-buddy-introduce#5]
### 내용
로그인을 할 때 express 서버로 요청을 하고, express 서버에서 깃으로 로그인 요청을 한 후에, 데이터를 가져와서 세션에 저장합니다.
이 과정에서 localhost:3000의 세션에 데이터를 저장하는게 아니라, localhost:5000의 세션에 데이터를 저장해서, 클라이언트에서 user정보를 가져오지 못하는 문제가 있습니다.

이러한 문제가 생기는 이유는 `passport` 자체가 CSR을 위한 모듈이 아니라 SSR을 위한 모듈이어서 그런 것 같습니다.

그래서 passport 모듈을 사용해서 로그인 하는게 아닌, 직접 url로 요청을 해서 액세스 토큰을 받아오는 방식으로 해야할 것 같습니다.

**Comment by cs801458j** [comment]
내용 확인했습니다. 
그런데 이해가 안되는 부분이있는데, 로컬호스트 포트가 다른곳에 데이터가 저장되면 시작할때 서비스하는 포트를 변경하는 방법은 안되는건가요?
바꿔야하는게 편하다면 바꾸는 것은 좋은데 어떤 이슈인지 잘 모르겠습니다.

**Comment by MaengMaeng** [comment]
`포트1`에서 로그인을 하면 `포트1`의 세션에 데이터가 저장되어야 하는데,
서버인 `포트2`에 저장이 되는 게 문제입니다.

보통 SSR의 경우, 서버에서 페이지를 보내줘서 포트가 같은데
CSR의 경우에는 프론트엔드의 포트와 서버의 포트가 달라서 발생하는 문제 같습니다.

**Comment by cs801458j** [comment]
아하 넵 알겠습니다
